on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-31 * *"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        timeout-minutes: 1
        with:
          node-version: 16

      - uses: microsoft/playwright-github-action@v1
      - name: run CodeceptJS tests
        run: |
          npm ci
          npm run test  
      
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Job failed :rocket:'
          SLACK_TITLE: Make WEB recording 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}